import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import NavBanner from "@/components/NavBanner";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div class="fixed -z-20 inset-0 h-[100%] w-full bg-neutral-50 bg-[radial-gradient(#e5e7eb_1px,transparent_1px)] [background-size:16px_16px]"></div>
        <NavBanner />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
