import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import NavBanner from "@/components/NavBanner";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavBanner />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
